defaults:
  - model_checkpoint
  - early_stopping
  - model_summary
  - rich_progress_bar
  - learning_rate_monitor
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}_{step:06d}_weighted_loss_{val/weighted_loss:.4f}"
  monitor: "val/weighted_loss"
  mode: "min"
  save_last: True
  auto_insert_metric_name: False
  save_top_k: 11

early_stopping:
  monitor: "val/weighted_loss"
  patience: 10
  mode: "min"

model_summary:
  max_depth: 1
