# @package _global_

defaults:
  - _self_
  - data: null
  - model: null
  - logger: csv
  - trainer: gpu
  - paths: default
  - extras: default
  - hydra: default

  - experiment: null
  - hparams_search: null
  - optional local: default
  - debug: null

task_name: "eval"

tags: ["dev"]

train: False
test: True
# passing checkpoint path is necessary for evaluation
ckpt_path: ???
seed: 42
